trigger:
  batch: true
  branches:
    include:
      - master
      - dev
      # TODO: make `main` the main branch
      - main 

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 14.x
  displayName: install Node.js

- script: |
    npm ci
  displayName: npm install

- script: |
    npm run lint
  displayName: npm run lint

- script: |
    npm run test:unit
  displayName: run unit tests

- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: 'test-results/test-results.xml'
    testRunTitle: Angular unit test run
  displayName: publish test results
  condition: always()

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'test-results/coverage/cobertura.xml'
    reportDirectory: coverage
  displayName: publish code coverage
  condition: always()

- script: |
    npm run build
  displayName: build the Cashmere library

- script: |
    # fail the script if any errors occur
    set -e

    cd dist/user-guide/

    # Copy redirection error page for Github Pages
    cp index.html 404.html

    # Redirect Cashmere Url to CNAME file
    echo $CASHMERE_URL > "CNAME"

    git config --global user.email "$(GIT_EMAIL)"
    git config --global user.name "$(GIT_USER_NAME)"
    git init
    git add .
    git commit -m "Committing built docs for GitHub Pages"
    git checkout -b gh-pages
    git remote add origin https://$(GITHUB_TOKEN)@github.com/HealthCatalyst/Fabric.Cashmere.git
    git push origin gh-pages --force
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  displayName: 'publish GitHub pages (Docs site)'
  
- script: |
    npx semantic-release
  displayName: 'publish NPM package'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    NPM_TOKEN: $(NPM_TOKEN)

