import {NgModule} from '@angular/core';
import {
    AccordionModule,
    AppSwitcherModule,
    BreadcrumbsModule,
    BannerModule,
    ButtonModule,
    CheckboxModule,
    ChipModule,
    DrawerModule,
    FormFieldModule,
    IconModule,
    InputModule,
    ListModule,
    ModalModule,
    NavbarModule,
    PaginationModule,
    PicklistModule,
    PopoverModule,
    ProgressIndicatorsModule,
    RadioButtonModule,
    SelectModule,
    SubnavModule,
    TabsModule,
    TableModule,
    TileModule,
    ToasterModule,
    TypeformSurveyModule
} from '@wcf-insurance/cashmere';

@NgModule({
    exports: [
        AccordionModule,
        AppSwitcherModule,
        BreadcrumbsModule,
        BannerModule,
        ButtonModule,
        CheckboxModule,
        ChipModule,
        DrawerModule,
        FormFieldModule,
        IconModule,
        InputModule,
        ListModule,
        ModalModule,
        NavbarModule,
        PaginationModule,
        PicklistModule,
        PopoverModule,
        ProgressIndicatorsModule,
        RadioButtonModule,
        SelectModule,
        SubnavModule,
        TableModule,
        TabsModule,
        TileModule,
        ToasterModule,
        TypeformSurveyModule
    ]
})
export class CashmereModule {}
